version: '3.6'

services:
  verdaccio:
    image: verdaccio/verdaccio:4.1.0
    ports:
      - 30001:4873
  gitea:
    image: gitea/gitea:1.8.3
    environment:
      - USER_UID=1000
      - USER_GID=1000
    ports:
      - "3000:3000"
      - "222:22"

