apiVersion: v1
kind: Service
metadata:
  name: gitea-svc
  labels:
    app: gitea
spec:
  type: NodePort
  ports:
  # - port: 22
  #   # nodePort: 22
  - port: 3000
    protocol: TCP
    nodePort: 30002
  selector:
    app: gitea
