version: "3.3"

services:
  gitea-1:
    image: gitea/gitea:1.8.3
    volumes:
      - ./app1.ini:/data/gitea/conf/app.ini
    ports:
      - "30001:3000"
      - "22001:22"
  gitea-2:
    image: gitea/gitea:1.8.3
    volumes:
      - ./app2.ini:/data/gitea/conf/app.ini
    ports:
      - "30002:3000"
      - "22002:22"
