name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: make -e BUILD_ENV=COMPOSE bootstrap
    - name: markdownlint
      run: make -e BUILD_ENV=COMPOSE markdownlint
    - name: validate
      run: make -e BUILD_ENV=COMPOSE validate
